[package]
name = "boot_proto"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Boot protocol types for RanyOS"

[dependencies]
ap_trampoline = { path = "../ap_trampoline" }
boot_config = { path = "../boot_config", default-features = false }
graphic_types = { path = "../graphic_types", default-features = false }
