[package]
name = "boot_proto"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Boot protocol types for RanyOS"

[dependencies]
graphic_types = { path = "../graphic_types", default-features = false }
