[package]
name = "qemu_suite_graphics"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "QEMU no_std graphics suite"

[dependencies]
graphic_types = { path = "../../libs/graphic_types", features = ["qemu-test-export"] }
exorust_apps = { path = "../../apps", features = ["qemu-test-export"] }
