[package]
name = "app_sdk"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Application SDK for ExoRust OS - the 'std' library for SPL applications"

[lints]
workspace = true

[lib]
name = "app_sdk"
path = "src/lib.rs"

[dependencies]
kernel_api = { path = "../../interfaces/kernel_api" }
