[package]
name = "standalone_driver_wrapper"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
kernel_api = { path = "../../interfaces/kernel_api" }
usb_driver = { path = "../../drivers/usb", optional = true }
nvme_driver = { path = "../../drivers/nvme", optional = true }
mlx5_driver = { path = "../../drivers/mlx5", optional = true }
virtio_driver = { path = "../../drivers/virtio", optional = true }

[features]
default = []
standalone = ["kernel_api/cell_runtime"]
driver-usb = ["dep:usb_driver"]
driver-nvme = ["dep:nvme_driver"]
driver-mlx5 = ["dep:mlx5_driver"]
driver-virtio = ["dep:virtio_driver"]
