[package]
name = "qemu-tests"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Host-side QEMU suite orchestrator"

[dependencies]
qemu_runner = { path = "../tools/qemu_runner" }
