[package]
name = "ide_driver"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "IDE Driver for RanyOS"

[dependencies]
spin = "0.9"
hal = { path = "../../hal" }
log = "0.4"
