[package]
name = "qemu_suite_kernel"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "QEMU no_std kernel migration suite"

[dependencies]
