[package]
name = "serial_driver"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Serial Driver for RanyOS"

[lints]
workspace = true

[dependencies]
exorust_sync = { path = "../../libs/sync" }
hal = { path = "../../hal" }
