#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

network_tree=(
  kernel/src/net
  kernel/src/net/security
)

fail() {
  echo "check-network-zero-copy-guard: $1" >&2
  exit 1
}

if rg -n "payload_span_to_vec\\(" "${network_tree[@]}" >/dev/null; then
  fail "found removed DHCP payload_span_to_vec helper"
fi

if rg -n "hostname:\\s*Vec<u8>" "${network_tree[@]}" >/dev/null; then
  fail "found Vec<u8> DHCP hostname event payload"
fi

if rg -n "domain_search:\\s*Vec<.*String>" "${network_tree[@]}" >/dev/null; then
  fail "found Vec<String> DHCPv6 domain_search event payload"
fi

if rg -n "BTreeMap<String,\\s*DnsCacheEntry>" "${network_tree[@]}" >/dev/null; then
  fail "found raw String DNS cache key"
fi

if rg -n "BTreeMap<String,\\s*MdnsCacheEntry>" "${network_tree[@]}" >/dev/null; then
  fail "found raw String mDNS cache key"
fi

if rg -n "vec_from_payload\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed TLS payload flatten helper"
fi

if rg -n "read_vec\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed read_vec-based parser or record path"
fi

if rg -n "packet_payload_from_slice\\(|packet_payload_from_parts\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed TLS packet payload builder helper"
fi

if rg -n "\\bOwnedPayloadRange\\b" "${network_tree[@]}" >/dev/null; then
  fail "found removed owned payload range abstraction"
fi

if rg -n "\\bsplit_payload_prefix_owned\\b|\\bdiscard_payload_prefix\\b" "${network_tree[@]}" >/dev/null; then
  fail "found removed payload split/discard owner duplication root"
fi

if rg -n "\\bPayloadPrefix\\b|\\bread_prefix\\b" "${network_tree[@]}" >/dev/null; then
  fail "found removed payload prefix materialization surface"
fi

if rg -n "\\bcopy_payload_prefix\\b|\\bappend_copied_prefix\\b|\\bowned_packet_payload\\b|\\bpacket_payload_from_frame\\b" \
  "${network_tree[@]}" kernel/src/test \
  >/dev/null; then
  fail "found removed packet payload materialization root"
fi

if rg -n "\\bpayload_span_to_string\\b|\\btyped_name\\b|\\btyped_value\\b" \
  "${network_tree[@]}" kernel/src/test \
  >/dev/null; then
  fail "found removed payload span text materialization accessor"
fi

if rg -n "\\bwrite_payload_view\\b|\\bwrite_payload_span_ref\\b|\\.write_data\\(" \
  kernel/src/net/l3/icmp kernel/src/net/l4/udp \
  >/dev/null; then
  fail "found removed ICMP/UDP payload copy writer"
fi

if rg -n "append_generated_bytes\\(&raw_packet|core::mem::take\\(&mut remaining_payload\\)|more_fragments \\|\\| offset != 0 \\|\\| fragment_data_len !=" \
  kernel/src/net/l3/ipv6/processor_impl.rs \
  kernel/src/net/runtime/stack/core_impl/mod.rs \
  kernel/src/net/runtime/stack/core_impl/send_v6.rs \
  >/dev/null; then
  fail "found removed ingress or fragmentation payload copy fallback"
fi

if ! rg -n "\\bTxOwnerGroupState\\b" kernel/src/net/runtime/device/mod.rs >/dev/null; then
  fail "missing TX owner group state for fragmented descriptor ownership"
fi

if rg -n "\\btx_bounce\\b|\\bbounce_tx\\b|\\blinearize_tx\\b|copy[^\\n]*tx[^\\n]*fallback|tx[^\\n]*copy[^\\n]*fallback" \
  "${network_tree[@]}" interfaces/kernel_api/src/netdev.rs \
  >/dev/null; then
  fail "found driver TX bounce/copy fallback"
fi

if rg -n "\\bpub fn split_at\\b|\\bsplit_at:\\s*unsafe fn|\\bfn [A-Za-z0-9_]*split_at\\b" \
  interfaces/kernel_api/src/types.rs kernel/src/net/datapath/mempool/mod.rs \
  >/dev/null; then
  fail "found removed PacketRef split backing surface"
fi

if rg -n "\\bPacketPayloadBuilder\\b|\\bappend_generated_bytes\\b|\\bappend_generated_str\\b|\\bfn push_bytes\\b|\\bfn push_str\\b" \
  kernel/src/net/payload.rs "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed broad PacketPayloadBuilder generated byte/string ingestion API"
fi

if rg -n "\\bpush_generated_bytes\\b|\\bpush_generated_str\\b" kernel/src/net/payload.rs "${network_tree[@]}" >/dev/null; then
  fail "found removed generated byte/string packet builder API"
fi

if rg -n "\\.(append_generated_bytes|append_generated_str|push_bytes)\\(" "${network_tree[@]}" >/dev/null; then
  fail "found call to removed broad PacketPayloadBuilder byte/string ingestion API"
fi

if rg -n "\\bfn slice\\b|\\.slice\\(" kernel/src/net/payload.rs "${network_tree[@]}" >/dev/null; then
  fail "found removed generic payload slice surface"
fi

if rg -n "\\bretain_payload_window_owned\\b|\\bPayloadRange::slice\\b|\\bPayloadSpanRef::slice\\b" "${network_tree[@]}" >/dev/null; then
  fail "found removed payload ownership window materializer"
fi

if rg -n "\\brecv_from_buffer\\b|\\bcopy_remaining_to\\b" "${network_tree[@]}" >/dev/null; then
  fail "found removed byte-buffer socket receive path"
fi

if rg -n "\\bPacketPool\\b|\\bPerCoreTxCache\\b|Vec<\\s*Vec\\s*<\\s*u8\\s*>\\s*>" "${network_tree[@]}" kernel/src/test >/dev/null; then
  fail "found removed byte-buffer TX pool"
fi

if rg -n "\\bsend_udp_addr\\b|\\btry_send_udp_packet_path\\b|\\bcalculate_checksum_bytes\\b|\\bcalculate_checksum_v6_bytes\\b" "${network_tree[@]}" kernel/src/test >/dev/null; then
  fail "found removed byte-slice TX/checksum API"
fi

if rg -n "\\bScatterGatherList\\b|\\bSgTxBuilder\\b|\\bHeaderCache\\b|\\bTsoContext\\b|\\bTsoEngine\\b|\\bTsoSegmentInfo\\b|\\bGroTable\\b|\\bGroSegment\\b|\\bheader_cache\\b|\\bscatter_gather\\b" "${network_tree[@]}" kernel/src/test >/dev/null; then
  fail "found removed dormant byte-buffer datapath surface"
fi

if rg -n "\\blinearize\\(" "${network_tree[@]}" >/dev/null; then
  fail "found removed scatter-gather linearization fallback"
fi

if rg -n "\\bHeapPacketBacking\\b|\\bHeapPacketState\\b" interfaces/kernel_api/src/types.rs >/dev/null; then
  fail "found removed heap packet backing"
fi

if rg -n "\\.clone\\(" "${network_tree[@]}" interfaces/kernel_api/src/netdev.rs interfaces/kernel_api/src/types.rs interfaces/kernel_api/src/services.rs >/dev/null; then
  fail "found clone call in network ownership scope"
fi

if rg -n "\\btry_clone_ref\\b|\\bclone_storage\\b" \
  "${network_tree[@]}" interfaces/kernel_api/src/types.rs interfaces/kernel_api/src/netdev.rs \
  >/dev/null; then
  fail "found removed PacketRef overlapping clone surface"
fi

if rg -n "#\\[derive\\([^\\]]*Clone[^\\]]*\\)\\]" "${network_tree[@]}" interfaces/kernel_api/src/netdev.rs interfaces/kernel_api/src/types.rs interfaces/kernel_api/src/services.rs \
  | rg -v "Copy" >/dev/null; then
  fail "found non-Copy Clone derive in network ownership scope"
fi

if rg -n "\\bArc<|\\bArc::new\\(" "${network_tree[@]}" interfaces/kernel_api/src/netdev.rs interfaces/kernel_api/src/types.rs interfaces/kernel_api/src/services.rs >/dev/null; then
  fail "found Arc ownership sharing in network scope"
fi

if rg -n "\\bpayload_span_from_slice\\(" "${network_tree[@]}" >/dev/null; then
  fail "found removed TLS slice-to-owned-payload helper"
fi

if rg -n "\\bcopy_all_into\\(" "${network_tree[@]}" >/dev/null; then
  fail "found removed full-payload copy helper"
fi

if rg -n "\\b(copy_into|copy_range|as_contiguous_slice)\\(" \
  kernel/src/net/payload.rs interfaces/kernel_api/src/types.rs \
  >/dev/null; then
  fail "found removed generic payload linearization surface"
fi

if rg -n "\\.(copy_into|copy_range|as_contiguous_slice)\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found retained generic payload linearization call"
fi

if rg -n "payload_preview_bytes\\(" "${network_tree[@]}" >/dev/null; then
  fail "found removed mlx5 payload preview linearization"
fi

if rg -n "\\bsplit_payload_owned\\b|\\bcopy_segment_range\\b|\\bcopy_span_to_packet\\b" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed packet payload split/copy root"
fi

if rg -n "\\bmove_payload_window_owned\\b" "${network_tree[@]}" >/dev/null; then
  fail "found removed raw usize owned payload window helper"
fi

if rg -n "\\bsubslice_offset\\b" \
  kernel/src/net/runtime/command_handler kernel/src/net/runtime/stack kernel/src/net/l3 \
  >/dev/null; then
  fail "found removed borrowed-slice ingress offset recovery"
fi

if rg -n "\\bclone_payload_window_owned\\b|\\bsend_icmp_echo_fallback\\b|\\brecord_recv_copy_fallback\\b|\\brecv_copy_fallback" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed network copy fallback root"
fi

if rg -n "Fallback to copy-based path|\\btake_payload_prefix\\s*\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed network copy fallback path"
fi

if rg -n "\\btls13_encrypt_application_payload\\(&|\\.encrypt\\(" \
  kernel/src/net/security/tls kernel/src/net/services/http \
  >/dev/null; then
  fail "found removed borrowed or byte-slice TLS encrypt API"
fi

if rg -n "\\baes_gcm_(encrypt|decrypt)_into\\b" \
  kernel/src/net/security/tls/connection \
  >/dev/null; then
  fail "found contiguous AES-GCM helper in TLS record path"
fi

if rg -n "\\brecv_buffer\\b" kernel/src/net/security/tls >/dev/null; then
  fail "found TLS byte-buffer receive state instead of record ingress queue"
fi

if rg -n "build_stack_payload\\(|enqueue_v6_send_bytes\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed DHCP/mDNS byte-to-payload helper"
fi

if rg -n "\\bpayload_as_contiguous_slice\\(|\\bpayload_from_packet_range\\(|\\bpayload_from_subslice\\(|\\bpayload_from_bytes\\(|\\bpacket_from_bytes\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed contiguous or packet extraction helper"
fi

if rg -n "PayloadSpan::from_bytes\\(|DnsNameView::from_labels\\(|DnsNameOwned::from_labels\\(|DnsTxtView::from_spans\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed payload span or DNS/TXT convenience constructor"
fi

if rg -n "to_owned_string\\(|to_lowercase_string\\(" "${network_tree[@]}" >/dev/null; then
  fail "found early text materialization in mDNS production path"
fi

if rg -n "DnsNameOwned::from_ascii_name|DnsNameOwned::from_view" "${network_tree[@]}" >/dev/null; then
  fail "found removed DNS owned-name string/view constructor"
fi

if rg -n "\\bprocess_single_record\\(|\\bdecrypt_record\\(|\\btls13_decrypt_record\\(" "${network_tree[@]}" >/dev/null; then
  fail "found removed TLS record ingress root"
fi

if rg -n "\\bsingle_chunk\\(|contiguous_payload_bytes" "${network_tree[@]}" >/dev/null; then
  fail "found removed contiguous payload TLS/X.509 boundary"
fi

if rg -n "\\bparse_x509\\(" kernel/src/net/security/tls kernel/src/net/security/x509 >/dev/null; then
  fail "found removed slice-based X.509 parser"
fi

if rg -n "&\\[&\\[u8\\]\\]|validate_certificate_chain\\([^\\n]*&\\[&\\[u8\\]" \
  kernel/src/net/security/x509 \
  >/dev/null; then
  fail "found removed slice-based X.509 API"
fi

if rg -n "TLS_1_[012]|TLS_RSA_WITH|_CBC_|\\btls12\\b|\\btls10\\b|aes_cbc|tls_add_padding|tls_verify_padding|derive_master_secret|derive_key_block|build_client_key_exchange|build_change_cipher_spec|build_client_finished_tls12" \
  kernel/src/net/security/tls kernel/src/net/services/http \
  >/dev/null; then
  fail "found removed TLS pre-1.3, CBC, or key-transport surface"
fi

if rg -n "skip_verify|should_skip_verify|client_cert:|client_key:|SessionCache|SessionTicket|SessionId" \
  kernel/src/net/security/tls kernel/src/net/services/http \
  >/dev/null; then
  fail "found removed TLS verification bypass, client-auth, or resumption state"
fi

if rg -n -e "rsa_pkcs1_encrypt\\(|\\bmgf1\\(|\\bhash_compute\\(" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed crypto owned-buffer helper"
fi

if rg -n -e "->\\s*(Option<)?Vec<u8>" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed Vec-returning crypto surface"
fi

if rg -n "server_name:\\s*Option<String>|alpn_protocols:\\s*Vec<String>|ca_certs:\\s*Vec<Certificate>|VecDeque<SessionCacheEntry>" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found removed Vec/String-based TLS config or session cache surface"
fi

if rg -n "packet\\.clone\\(|payload\\.clone\\(|PacketPayload::single\\(packet\\.clone\\)" \
  "${network_tree[@]}" \
  >/dev/null; then
  fail "found retained clone root in network/security tree"
fi

if rg -n "\\bZeroCopyBuffer\\b|\\bZeroCopyWriter\\b|\\bSgList\\b|\\bDmaSgEntry\\b|datapath::zero_copy|mod zero_copy|pub mod zero_copy" \
  kernel/src/net kernel/src/test interfaces/kernel_api/src/netdev.rs interfaces/kernel_api/src/resource/net.rs interfaces/kernel_api/src/types.rs \
  >/dev/null; then
  fail "found removed zero_copy buffer facade"
fi

if rg -n "\\btransmit_bytes_internal\\b|\\btransmit_bytes_with_meta_internal\\b" \
  kernel/src/net \
  >/dev/null; then
  fail "found removed byte-slice TX runtime surface"
fi

if rg -n "\\bprocess_on\\([^\\n]*&\\[u8\\]|\\bprocess_v6_on\\([^\\n]*&\\[u8\\]|\\bprocess_with_packet(_v6)?_on\\b" \
  kernel/src/net/l4/udp kernel/src/net/runtime kernel/src/net/tests \
  >/dev/null; then
  fail "found removed byte-slice UDP ingress surface"
fi

if rg -n "pub enum ProcessResult<'|pub enum Ipv4ProcessResult<'|pub enum Ipv6ProcessResult<'|\\bprocess_with_time_and_packet\\b|\\bprocess_with_packet\\(" \
  kernel/src/net/l2/ethernet kernel/src/net/l3 kernel/src/net/runtime \
  >/dev/null; then
  fail "found removed borrowed L2/L3 ingress result or processor API"
fi

if rg -n "pub struct NetTxSegment[[:space:]]*\\{|pub cpu_ptr:|pub device_addr:|pub len:" \
  interfaces/kernel_api/src/netdev.rs \
  >/dev/null; then
  fail "found public raw NetTxSegment descriptor fields"
fi

if rg -n "PacketRef::from_vec|PacketPayload::from_vec|PacketPayload::into_vec|\\.to_vec\\(\\)" \
  kernel/src/net interfaces/kernel_api/src \
  >/dev/null; then
  fail "found removed test-only packet materializer"
fi

echo "check-network-zero-copy-guard: ok"
