with open('scripts/run.ps1', 'r', encoding='utf-8') as f:
    s = f.read()
print('curly_open', s.count('{'))
print('curly_close', s.count('}'))
print('paren_open', s.count('('))
print('paren_close', s.count(')'))
print('brack_open', s.count('['))
print('brack_close', s.count(']'))
print('double_quotes', s.count('"'))
print('single_quotes', s.count("'"))