#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

INPUT_FILES=(
  "${REPO_ROOT}/kernel/src/qemu_tests.rs"
  "${REPO_ROOT}/kernel/src/qemu_tests/wave8_net_tests.rs"
  "${REPO_ROOT}/kernel/src/qemu_tests/wave8_net_tests/net_peripheral_tests.rs"
)

OUTPUT_FILE="${REPO_ROOT}/kernel/src/qemu_tests/generated/network_case_table.rs"
mkdir -p "$(dirname "${OUTPUT_FILE}")"

mapfile -t CASES < <(
  rg -No --no-filename '^pub (async )?fn (net_[a-zA-Z0-9_]+_smoke|kernel_net_[a-zA-Z0-9_]+_smoke)\(' "${INPUT_FILES[@]}" \
    | sed -E 's/^pub (async )?fn ([^(]+)\(.*/\1\2/' \
    | LC_ALL=C sort -u
)

if [[ "${#CASES[@]}" -eq 0 ]]; then
  echo "No network runtime cases were found" >&2
  exit 1
fi

{
  echo "// @generated by scripts/gen_network_runtime_cases.sh"
  echo "// DO NOT EDIT MANUALLY"
  echo
  echo "use super::NetworkRuntimeCase;"
  echo
  echo "pub(super) static NETWORK_RUNTIME_CASES: &[(&str, NetworkRuntimeCase)] = &["
  for case_name in "${CASES[@]}"; do
    if [[ "$case_name" == "async "* ]]; then
      async_name="${case_name#async }"
      printf '    ("%s", NetworkRuntimeCase::Async(|| alloc::boxed::Box::pin(crate::qemu_tests::%s()))),\n' "$async_name" "$async_name"
    else
      printf '    ("%s", NetworkRuntimeCase::Sync(crate::qemu_tests::%s)),\n' "$case_name" "$case_name"
    fi
  done
  echo "];"
} > "${OUTPUT_FILE}"

echo "Generated ${OUTPUT_FILE} with ${#CASES[@]} cases"
