#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

INPUT_FILES=(
  "${REPO_ROOT}/kernel/src/qemu_tests.rs"
  "${REPO_ROOT}/kernel/src/qemu_tests/wave8_net_tests.rs"
  "${REPO_ROOT}/kernel/src/qemu_tests/wave8_net_tests/net_endpoint_tests.rs"
  "${REPO_ROOT}/kernel/src/qemu_tests/wave8_net_tests/net_peripheral_tests.rs"
)

OUTPUT_FILE="${REPO_ROOT}/kernel/src/qemu_tests/generated/network_case_table.rs"
mkdir -p "$(dirname "${OUTPUT_FILE}")"

mapfile -t CASES < <(
  rg -No --no-filename '^pub fn (net_[a-zA-Z0-9_]+_smoke|kernel_net_[a-zA-Z0-9_]+_smoke)\(' "${INPUT_FILES[@]}" \
    | sed -E 's/^pub fn ([^(]+)\(.*/\1/' \
    | LC_ALL=C sort -u
)

if [[ "${#CASES[@]}" -eq 0 ]]; then
  echo "No network runtime cases were found" >&2
  exit 1
fi

{
  echo "// @generated by scripts/gen_network_runtime_cases.sh"
  echo "// DO NOT EDIT MANUALLY"
  echo
  echo "pub static NETWORK_RUNTIME_CASES: &[(&str, fn() -> bool)] = &["
  for case_name in "${CASES[@]}"; do
    printf '    ("%s", crate::qemu_tests::%s),\n' "${case_name}" "${case_name}"
  done
  echo "];"
  echo
  echo "pub const NETWORK_RUNTIME_CASE_COUNT: usize = NETWORK_RUNTIME_CASES.len();"
} > "${OUTPUT_FILE}"

echo "Generated ${OUTPUT_FILE} with ${#CASES[@]} cases"
