[package]
name = "exorust_apps"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "ExoRust System Applications"

[lib]
name = "exorust_apps"
path = "src/lib.rs"

[dependencies]
app_sdk = { path = "../libs/app_sdk" }
graphic_types = { path = "../libs/graphic_types", features = ["alloc"] }

[features]
default = []
qemu-test-export = []
