[package]
name = "exorust_apps"
version = "0.1.0"
edition = "2024"
authors = ["ExoRust Team"]
description = "ExoRust System Applications"

[lib]
name = "exorust_apps"
path = "src/lib.rs"

[dependencies]
kernel_api = { path = "../interfaces/kernel_api" }
graphic_types = { path = "../libs/graphic_types" }
