[package]
name = "cap_harness"
version = "0.1.0"
edition = "2024"
authors = ["ExoRust Team"]
license = "MIT"
repository = "https://github.com/Start-Rany-OS/Rany_OS"
readme = "README.md"
keywords = ["os", "kernel", "rust"]
categories = ["os"]
description = "Capability Test Harness for RanyOS"

[lints]
workspace = true

[dependencies]

[features]
default = []
host-tests = []
