[package]
name = "fat32"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
description = "FAT32 Filesystem implementation for RanyOS"
categories.workspace = true

[lib]
name = "fat32"
path = "src/lib.rs"

[dependencies]
vfs = { path = "../../libs/vfs" }
spin = "0.9.8"
log = "0.4"

[features]
debug-trace = []
