[package]
name = "ahci_driver"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "AHCI Driver for RanyOS"

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
# HAL for MMIO and port I/O wrappers
hal = { path = "../../hal" }
kernel_api = { path = "../../interfaces/kernel_api" }

[features]
default = []
